### ISSUE TITLE
codecheck step for 'core_no_deps_RelWithDebInfo' Error 2

### ISSUE THREAD

**Issue by osrf-migration** [ignitionrobotics/ign-cmake#66] opened 2019-09-23 21:35 UTC
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-cmake/issues/66)) by Anonymous.**

----------------------------------------
Trying to build branch **default**, my environment:

```console
longervision-GT72-6QE% lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 19.04
Release:	19.04
Codename:	disco
longervision-GT72-6QE% gcc --version
gcc (Ubuntu 8.3.0-6ubuntu1) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

And, I obtained the following **ERROR** message if I enable **BUILD_TESTING**

```
#!cmake


[ 40%] Performing codecheck step for 'core_no_deps_RelWithDebInfo'
cd ....../IgnitionRobotics/libs/ign-cmake/build/examples && make -C ....../IgnitionRobotics/libs/ign-cmake/build/examples/core_no_deps_RelWithDebInfo-prefix/src/core_no_deps_RelWithDebInfo-build codecheck
make[3]: Entering directory '....../IgnitionRobotics/libs/ign-cmake/build/examples/core_no_deps_RelWithDebInfo-prefix/src/core_no_deps_RelWithDebInfo-build'
make[4]: Entering directory '....../IgnitionRobotics/libs/ign-cmake/build/examples/core_no_deps_RelWithDebInfo-prefix/src/core_no_deps_RelWithDebInfo-build'
make[5]: Entering directory '....../IgnitionRobotics/libs/ign-cmake/build/examples/core_no_deps_RelWithDebInfo-prefix/src/core_no_deps_RelWithDebInfo-build'
make[6]: Entering directory '....../IgnitionRobotics/libs/ign-cmake/build/examples/core_no_deps_RelWithDebInfo-prefix/src/core_no_deps_RelWithDebInfo-build'
make[6]: Leaving directory '....../IgnitionRobotics/libs/ign-cmake/build/examples/core_no_deps_RelWithDebInfo-prefix/src/core_no_deps_RelWithDebInfo-build'
make[6]: Entering directory '....../IgnitionRobotics/libs/ign-cmake/build/examples/core_no_deps_RelWithDebInfo-prefix/src/core_no_deps_RelWithDebInfo-build'
make[6]: *** [CMakeFiles/codecheck.dir/build.make:59: CMakeFiles/codecheck] Error 1
make[6]: Leaving directory '....../IgnitionRobotics/libs/ign-cmake/build/examples/core_no_deps_RelWithDebInfo-prefix/src/core_no_deps_RelWithDebInfo-build'
make[5]: *** [CMakeFiles/Makefile2:142: CMakeFiles/codecheck.dir/all] Error 2
make[5]: Leaving directory '....../IgnitionRobotics/libs/ign-cmake/build/examples/core_no_deps_RelWithDebInfo-prefix/src/core_no_deps_RelWithDebInfo-build'
make[4]: *** [CMakeFiles/Makefile2:149: CMakeFiles/codecheck.dir/rule] Error 2
make[4]: Leaving directory '....../IgnitionRobotics/libs/ign-cmake/build/examples/core_no_deps_RelWithDebInfo-prefix/src/core_no_deps_RelWithDebInfo-build'
make[3]: *** [Makefile:223: codecheck] Error 2
make[3]: Leaving directory '....../IgnitionRobotics/libs/ign-cmake/build/examples/core_no_deps_RelWithDebInfo-prefix/src/core_no_deps_RelWithDebInfo-build'
make[2]: *** [examples/CMakeFiles/core_no_deps_RelWithDebInfo.dir/build.make:129: examples/core_no_deps_RelWithDebInfo-prefix/src/core_no_deps_RelWithDebInfo-stamp/core_no_deps_RelWithDebInfo-codecheck] Error 2
make[2]: Leaving directory '....../IgnitionRobotics/libs/ign-cmake/build'
make[1]: *** [CMakeFiles/Makefile2:1517: examples/CMakeFiles/core_no_deps_RelWithDebInfo.dir/all] Error 2
make[1]: Leaving directory '....../IgnitionRobotics/libs/ign-cmake/build'
make: *** [Makefile:166: all] Error 2

```

Any suggestions please?

**Comment by scpeters** [comment] 2020-12-18 22:27
duplicate of #62

**Closed by scpeters** 2020-12-18 22:27 UTC
Labels: bug, major
