### ISSUE TITLE
👨‍🌾 Problem comping on Windows for ign-cmake2

### ISSUE THREAD

**Issue by caguero** [ignitionrobotics/ign-cmake#140] opened 2020-12-29 15:55 UTC
https://build.osrfoundation.org/job/ignition_cmake-ci-ign-cmake2-windows7-amd64/57/console

Error message:

```
cl : Command line warning D9025 : overriding '/W3' with '/W4'
nonvirtual_destructor.cc
D:\Jenkins\workspace\ignition_cmake-ci-ign-cmake2-windows7-amd64\ws\ign-cmake\test\warning\nonvirtual_destructor.cc(28): error C2220: the following warning is treated as an error
```

On December 15 the job worked, and since December 22 we have the issue.

**Comment by chapulina** [comment] 2020-12-29 19:05
I think this is the new warning:

```
D:\Jenkins\workspace\ignition_cmake-ci-ign-cmake2-windows7-amd64\ws\ign-cmake\test\warning\nonvirtual_destructor.cc(28): warning C5205: delete of an abstract class 'Base' that has a non-virtual destructor results in undefined behavior
```

This is probably caused by an upgrade of Visual Studio on the CI machines. That warning was introduced in [VS 2019 v16.5](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warnings-by-compiler-version?view=msvc-160#warnings-introduced-in-visual-studio-2019-version-165-compiler-version-1925286100). That CI machine (` win-windows_local.win8`) is running v16.8.3. While testing a fix, I noticed that `win-windows_nuc.win10` is running v16.4.3, so this may look like a flaky test depending on where it runs.

I have a potential fix in https://github.com/ignitionrobotics/ign-cmake/pull/141.

**Comment by mjcarroll** [comment] 2021-01-05 16:42
#141 is merged

**Comment by chapulina** [comment] 2021-01-05 18:47
CI is :large_blue_circle: 

https://build.osrfoundation.org/job/ignition_cmake-ci-ign-cmake2-windows7-amd64/

**Closed by chapulina** 2021-01-05 18:47 UTC
Labels: Windows
